### ISSUE TITLE
Shortcuts no longer working

### ISSUE THREAD

**Issue by JC-BBO** [stanmaz/BBOalert#10]
![bbo-shortcuts](https://user-images.githubusercontent.com/84449339/151177602-4dedbe8c-c66d-4c7f-b565-b2b8901b923d.png)
Hi Stanmaz,
Lastnight none of my shortcuts worked.
Everything else as far as I could tell worked, i.e. automated alerts

The difference I noted was that BBO was now storing and presenting back what I had typed previously
I'm using Chrome

**Comment by stanmaz** [comment]
BBO changed the structure of chat controls. The issue will be fixed within few hours.

**Comment by JC-BBO** [comment]
Wow, excellent responsiveness.
Thanks for all your hard work

**Comment by stanmaz** [comment]
fixed in 6.6.1.5
