### ISSUE TITLE
Side Tab Issue

### ISSUE THREAD

**Issue by ADavidBailey** [stanmaz/BBOalert#15]
When the BBOalert side panel is open, clicking on a right-side BBO tab, closes the BBOalert side panel AND toggles the BBO side panel.

Please change it so that it opens the BBO side panel...

- If it's closed open it
- If it's open leave it open

With this change, the BBO side tabs would work the same with or without BBOalert

**Comment by ADavidBailey** [comment]
Thanks for the BBOalert button!!!

**Comment by ADavidBailey** [comment]
Oops!  This needs to be re-opened.  At first, I thought the BBOalert button fixed it; but, it did not.

**Comment by ADavidBailey** [comment]
With BBO panel open, you can see which BBO tab is active, behind it.  It's blue.
<img width="591" alt="Screenshot 2024-09-26 at 5 48 03 PM" src="https://github.com/user-attachments/assets/4b0fa014-c0c2-45d7-895c-82ef9c9adaca">
If you click it, you get this.
<img width="397" alt="Screenshot 2024-09-26 at 5 48 24 PM" src="https://github.com/user-attachments/assets/0e118c3a-3e7d-4487-a745-1cd853367d8d">
If you click one of the white buttons, it opens & turns blue.

**Comment by stanmaz** [comment]
Done : Version 8.3

**Comment by ADavidBailey** [comment]
Bravo!  Thank you very much.
