### ISSUE TITLE
Settings Menu

### ISSUE THREAD

**Issue by ADavidBailey** [stanmaz/BBOalert#16]
My BAD.  I found the settings menu. 

I still think you have an issue on the Documents tab.  The Release Notes is all that's there.
The Documents tab persistently shows Release Notes.

<img width="702" alt="Screenshot 2024-09-26 at 10 08 12 AM" src="https://github.com/user-attachments/assets/fe710f84-cf59-4eb9-b081-79061e5ac70b">

It does not collapse when I click the green title bar.

**Comment by stanmaz** [comment]
[image: image.png]

After you check it, the tab will  disappear and the button is displayed in
the right/upper corner of the screen.

[image: image.png]
