### ISSUE TITLE
How to have bidding scenarios

### ISSUE THREAD

**Issue by Pinticus** [stanmaz/BBOalert#17]
I've installed the latest version available, but I don't have the bidding scenarios available, how can I add them?

Using Chrome, BBO latest version

**Comment by stanmaz** [comment]
See the documentation :

https://tinyurl.com/Practice-Bidding-on-BBO
<https://tinyurl.com/Practice-Bidding-on-BBO?fbclid=IwZXh0bgNhZW0CMTAAAR2S_PTQujcJ3OneWFFIxHHz0_PSIXd1XErNPSlHOEvkwWXacEin5RgD_X8_aem_rrddrzuAjMnSsgOqJwwRQQ>

Section *Installing Practice Bidding Scenarios *p. 2 an 3
